config/routes.rb
Rails.application.routes.draw do  
  resources :sales do
  	resources :portions	
  end
  get 'home/index'

  root 'home#index'
  resources :menus

  resources :foods do
  	resources :ingredients
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :foods
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :description, :color)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <label >Menu</label>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <br>

  <div class="field">
    <label >Descripción</label>
    <%= form.text_area :description, class: "form-control Froala", id: "description" %>
  </div>

  <br>

  <div class="field">
    <label >Color</label>
    <%= form.color_field :color, id: :category_color , class: "form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Crear Menu", class: "btn btn-primary" %>
  </div>

  <script>
    $('#description').trumbowyg();
  </script>
<% end %>

app/views/menus/_menusdisponibles.html.erb
<div class="container">
	<h2>Menus del Dia </h2>
	<p><i><%= Date.today.to_s %></i></p>
	<div class="row">
		<% @menus.each do |m| %>
		<div class="col">
			<div class="card" style="width: 18rem; background-color: <%= m.color %>">
			  <div class="card-body">
			    <h5 class="card-title"><%= link_to m.name, menu_url(m), class: "card-title" %></h5>

			    <% if m.foods.any? %>
			    	    	<% m.foods.each do |f| %>

			    				<ul class="list-group list-group-flush" >
			    				  <li class="list-group-item" style="background-color: <%= m.color %>"><%= f.name %> 
			    				  <% if f.portions.count > 0 %>			    	  	
			    				   <span class="text-right badge badge-secondary"><%= f.portions.count %></span>
			    				   <% end %>
			    				   </li>
			    				</ul>

			    	    	<% end %>
			    <% else %>
			    	<ul class="list-group list-group-flush">
			    		<li class="list-group-item" style="background-color: <%= m.color %>">
			    			<div class="text-center">
			    				<p><i>No hay comidas</i></p>
			    			</div>
			    		</li>
			    	</ul>
			    <% end  %>
			  </div>
			</div>	
		</div>
		<% end %>
	</div>
</div>




			    	
				    	

app/views/menus/edit.html.erb
<div class="container">
	<h3>Editar Menu: <%= @menu.name %></h3>

	<%= render 'form', menu: @menu %>	
</div>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Menus</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Menu</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @menus.each do |menu| %>
        <tr>
          <td><%= link_to menu.name, menu %></td>          
          <td><%= link_to link_badge('warning','fa-edit'), edit_menu_path(menu) %></td>
          <td><%= link_to link_badge('danger','fa-trash-alt'), menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Menu', new_menu_path, class: "btn btn-primary" %>
  <%= link_to 'Comidas', foods_path, class: "btn btn-primary" %>
  
</div>

app/views/menus/new.html.erb
<div class="container">
	<h1>Nuevo Menu</h1>

	<%= render 'form', menu: @menu %>
	
</div>

app/views/menus/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<h2 style="color: <%= @menu.color %>">Menu: <%= @menu.name %></h2>
	<div>
		<%= @menu.description.html_safe %>
	</div>

	<h4>Comidas</h4>
	<% if @menu.foods.any? %>
		<table class="table">
		  <tr>
		    <th>Nombre</th>
		    <th>Precio</th>
		    <th>Menu</th>
		    <th colspan="3"></th>
		  </tr>
		  <%= render @menu.foods %> <br>
		</table>	
	<% else %>
		<p><i>No hay comidas</i></p>
	<% end %>


	<%= link_to 'Editar', edit_menu_path(@menu) %>
</div>