config/routes.rb
Rails.application.routes.draw do  
  resources :sales do
  	resources :portions	
  end
  get 'home/index'

  root 'home#index'
  resources :menus

  resources :foods do
  	resources :ingredients
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :set_food

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.food = @food
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient.food, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient.food }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient.food, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_food
      @food = Food.find(params[:food_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description, :quantity, :total_price, :food_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for([@food, @ingredient]) do |form| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Ingrediente</label>
    <%= form.text_field :name, id: :ingredient_name, class: "form-control" %>
  </div>

  <div class="field">
    <label>Descripción</label>
    <%= form.text_field :description, id: :ingredient_description, class: "form-control" %>
  </div>

  <div class="field">
    <label>Cantidad</label>
    <%= form.text_field :quantity, id: :ingredient_quantity, class: "form-control" %>
  </div>

  <div class="field">
    <label>Precio</label>
    <%= form.text_field :total_price, id: :ingredient_total_price, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Agregar Ingrediente", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<tr>
  <td><%= ingredient.quantity %></td>
  <td><%= link_to ingredient.name, food_ingredients_path(ingredient.food,ingredient) %></td>
  <td><%= ingredient.total_price %></td>
  
  <td><%= link_to 'Edit', edit_food_ingredient_path(ingredient.food,ingredient) %></td>
  <td><%= link_to 'Destroy', food_ingredients_path(ingredient.food,ingredient), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @ingredients %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ingredient.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ingredient.quantity %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @ingredient.total_price %>
</p>

<p>
  <strong>Food:</strong>
  <%= @ingredient.food %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>