config/routes.rb
Rails.application.routes.draw do  
  resources :sales do
  	resources :portions	
  end
  get 'home/index'

  root 'home#index'
  resources :menus

  resources :foods do
  	resources :ingredients
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :food
  belongs_to :sale
end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController
  before_action :set_portion, only: [:show, :edit, :update, :destroy]
  before_action :set_sale
  # GET /portions
  # GET /portions.json
  def index
    @portions = Portion.all
  end

  # GET /portions/1
  # GET /portions/1.json
  def show
  end

  # GET /portions/new
  def new
    @portion = Portion.new
  end

  # GET /portions/1/edit
  def edit
  end

  # POST /portions
  # POST /portions.json
  def create
    @portion = Portion.new(portion_params)
    @portion.sale = @sale   
    if @portion.quantity
      @portion.total = @portion.food.price * @portion.quantity      
    end
    respond_to do |format|
      if @portion.save
        format.html { redirect_to @sale, notice: 'Portion was successfully created.' }
        format.json { render :show, status: :created, location: @portion }
      else
        format.html { render :new }
        format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portions/1
  # PATCH/PUT /portions/1.json
  def update
    respond_to do |format|
      if @portion.update(portion_params)
        format.html { redirect_to @portion, notice: 'Portion was successfully updated.' }
        format.json { render :show, status: :ok, location: @portion }
      else
        format.html { render :edit }
        format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portions/1
  # DELETE /portions/1.json
  def destroy
    @portion.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Portion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_sale
      @sale = Sale.find(params[:sale_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_portion
      @portion = Portion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portion_params
      params.require(:portion).permit(:food_id, :sale_id, :quantity)
    end
end

app/helpers/portions_helper.rb
module PortionsHelper
end

app/views/portions/_form.html.erb
<%= form_for([@sale, @portion]) do |form| %>
  <% if @portion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portion.errors.count, "error") %> prohibited this portion from being saved:</h2>

      <ul>
      <% @portion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.collection_select(:food_id , Food.all, :id, :name, :prompt => 'Comida') %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :portion_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portions/_portion.html.erb
<tr>
  <td><%= portion.food.name %></td>
    <td><%= portion.food.price %></td>
  <td><%= portion.quantity %></td>
  <td><%= portion.total %></td>
</tr>

app/views/portions/edit.html.erb
<h1>Editing Portion</h1>

<%= render 'form', portion: @portion %>

<%= link_to 'Show', @portion %> |
<%= link_to 'Back', portions_path %>

app/views/portions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portions</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Sale</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @portions %>
  </tbody>
</table>

<br>

<%= link_to 'New Portion', new_portion_path %>

app/views/portions/new.html.erb
<h1>New Portion</h1>

<%= render 'form', portion: @portion %>

<%= link_to 'Back', sale_portions_path %>

app/views/portions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @portion.food %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @portion.sale %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @portion.quantity %>
</p>

<%= link_to 'Edit', edit_portion_path(@portion) %> |
<%= link_to 'Back', portions_path %>