config/routes.rb
Rails.application.routes.draw do  
  resources :sales do
  	resources :portions	
  end
  get 'home/index'

  root 'home#index'
  resources :menus

  resources :foods do
  	resources :ingredients
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
	has_many :portions
	before_create :init_total

	def set_total
		self.portions.each do |p|
			@t = @t.to_f + (p.quantity * p.food.price.to_f)			
		end
		self.update(total: self.total.to_f + @t.to_f)
				
	end

	private
	def init_total
		self.total = 0
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @portion = Portion.new
    @sale.set_total
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:status, :total, :shippedDate)
    end

    def total_sale

    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label> Estado</label>
    <%= form.text_field :status, id: :sale_status, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <label> Fecha de Entrega</label><br>
   <%= form.datetime_field :shippedDate, id: :sale_shippedDate, class: "form-control", type: "date" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Enviar" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<tr>
  <td class="text-center"><%= link_to sale.id, sale %></td>
  <td><%= sale.status %></td>
  <td><%= sale.total %></td>
  <td><%= sale.shippedDate %></td>
  <td><%= link_to link_badge('warning','fa-edit'), edit_sale_path(sale) %></td>
  <td><%= link_to link_badge('danger','fa-trash-alt'), sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/sales/edit.html.erb
<div class="container">
	<h3>Editar Pedido n°: <%= @sale.id %></h3>

	<%= render 'form', sale: @sale %>

</div>

app/views/sales/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Pedidos</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Pedido n°</th>
        <th>Estado</th>
        <th>Total</th>
        <th>Fecha de Entrega</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @sales %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Pedido', new_sale_path, class: "btn btn-primary" %>

  
</div>

app/views/sales/new.html.erb
<div class="container">
	<h1>Nuevo Pedido</h1>

	<%= render 'form', sale: @sale %>
</div>

app/views/sales/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<div class="row">
		<div class="col-s-2">
			<h4>Pedido n°: <%= @sale.id %></h4>

			<p>
			  <strong>Estado del Pedido:</strong>
			  <%= @sale.status %>
			</p>

			<p>
			  <strong>Total a Pagar:</strong>
			  <%= @sale.total %>
			</p>

			<p>
			  <strong>Fecha de Entrega:</strong>
			  <%= @sale.shippedDate %>
			</p>
		</div>
		<div class="col-s-10">
			<h3>Detalle</h3>
			<table>
			  <thead>
			    <tr>
			      <th>Comida</th>
			      <th>Precio</th>
			      <th>Cantidad</th>
			      <th>Subtotal</th>
			    </tr>
			  </thead>

			  <tbody>
			    <%= render @sale.portions %>
			  </tbody>
			</table>
		</div>
	</div>
	

	



	<div>
		<h5>Nueva Porcion</h5>
		<%= render 'portions/form' %>
	</div>

	<%= link_to 'Edit', edit_sale_path(@sale) %> |
	<%= link_to 'Back', sales_path %>
</div>